[package]
name = "addition"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[profile.release]
strip = true
opt-level = "z"
panic = "abort"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
swp = { path = "../../swp" }
